/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BuildAIConnections: typeof import('./src/components/SubComponents/BuildAIConnections.vue')['default']
    Dashboard: typeof import('./src/components/SubComponents/Dashboard.vue')['default']
    Destination: typeof import('./src/components/SubComponents/Destination.vue')['default']
    Dummy: typeof import('./src/components/SubComponents/dummy.vue')['default']
    FileInstructions: typeof import('./src/components/FileInstructions.vue')['default']
    Help: typeof import('./src/components/SubComponents/Help.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NavigationDrower: typeof import('./src/components/NavigationDrower.vue')['default']
    Pipelines: typeof import('./src/components/SubComponents/pipelines.vue')['default']
    Profile: typeof import('./src/components/Profile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./src/components/SubComponents/Settings.vue')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    Source: typeof import('./src/components/SubComponents/Source.vue')['default']
    Transformation: typeof import('./src/components/SubComponents/Transformation.vue')['default']
    Workspace: typeof import('./src/components/SubComponents/Workspace.vue')['default']
  }
}
